services:
  # react-app:
  #   image: fe-meeting-room_booking_system:first
  #   depends_on:
  #     - nest-app
  #   ports:
  #     - "80:80"
  #   networks:
  #     - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./.Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - "3105:3105"
    networks:
      - common-network
    restart: always
  mysql-container:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /Users/zhaojuntong/Desktop/dockertest/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: admin0326
    networks:
      - common-network
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集
    restart: always
  redis-container:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/zhaojuntong/Desktop/dockertest/redis:/data
    networks:
      - common-network
    restart: always
networks:
  common-network:
    driver: bridge
# name: react_nest_app_meeting_room_booking_system